import numpy as np

seizure_onset_zone = {
    "PY16N006": ["None"],
    "PY16N008": ["RATS3", "RATS4", "RATI5", "RATI6", "RATI7", "RATI8", "RATI13",
                 "RATI14", "RATI15", "RATI16"],
    "PY16N013": ["LDC3", "LDC4", "LDB3", "LDB4"],
    "PY17N005": ["LTG125", "LTG126", "LTG127", "LTG128"],
    "PY17N008": ["PLSD2", "PLSD3", "PLSD4", "PLSD5", "PLSD6", "PLSD7", "PLSD8",
                 "ASLD3", "ASLD4", "ASLD5", "ASLD6", "ASLD7", "ASLD8", "PSLD4",
                 "PSLD5", "PSLD6", "PSLD7", "PSLD8", "LD3", "LD4", "LD5", "LD6",
                 "LD7", "LD8", "ILD6", "ILD7", "ILD8", "RGF20", "RGF21", "RGF22",
                 "RGF28", "RGF29", "RGF36"],
    "PY17N014": ["LFA4", "LFA5", "LFA6", "LFA7", "LFA8", "LFS1", "LFS2", "LFS3"],
    "PY17N019": ["LFA4", "LFA5", "LFA6", "LFA7", "LFA8", "LFS1", "LFS2", "LFS3"],
    "PY17N020": ["LPC6", "LPC7", "LPC8", "LIH25", "LIH26", "LIH27", "LFG42", "LFG56",
                 "LFG57", "LFG62", "LFG63"],
    "PY18N002": ["RHD1", "RHD2", "RAD1", "RAD2", "LMFD1", "LMFD2", "LOFD1", "LOFD2"],
    "PY18N003": ["RAD1", "RAD2", "RAD3", "RAD4", "RHAD4", "RHAD5", "RHAD6", "RHAD7",
                 "RFTG52", "RFTG53" "RFTG54", "RFTG5", "RFTG13", "RFTG23"],
    "PY18N013": ["LPT1", "LPT2", "LPT3", "LPT4", "LSTA1", "LSTA2", "LMTA2"],
    "PY18N015": ["LOF1", "LA1", "LA2", "LA3", "LH1", "LH2", "LH3"],
    "PY18N016": ["LIPF1", "LIPF2", "LIPF3", "LIPF4", "LIF4", "LIF5", "LIF6", "LIF7",
                 "LI1", "LI2", "LI3", "LI4", "LI5"],
    "PY19N009": ["RAH1", "RAH2", "RPH1", "RPH2", "RA4", "RA5", "RA6", "RA7"],
    "PY19N012": ["LIN1", "LIN2", "LAH1", "LAH2"],
    "PY19N023": ["RA1", "RA2", "RAH1", "RAH2", "RPH1", "RPH2", "RMI3", "RMI4", "RMI5",
                 "RMM5", "RMM6"],
    "PY19N026": ["RAM1", "RAM2", "RAM3", "RAM4", "RAH1", "RAH2", "RAH3", "RPH1",
                 "RPH2", "RPH3", "RPHG1", "RPHG2", "RPHG3"],
    "PY20N001": ["LPH1", "LPH2", "LAH1", "LAH2", "LA1", "LA2"],
    "PY20N012": ["LAH1", "LAH2", "LAM1", "LAM2", "LPH1", "LPH2", "LPH3"],
    "PY21N002": ["5LS5", "5LS6", "1LL1", "1LL2", "1LL3", "1LL4", "2LL5", "2LL6",
                 "3LL4", "3LL5", "3LL6", "3LL7", "3LL8", "4LL6", "4LL7", "4LL8"],
    "PY21N004": ["LAH1", "BTA1", "BTA2", "LFT33", "LFT34", "LFT35", "LFT41",
                 "LFT42", "LFT43", "LFT44", "LFT49", "LFT50", "LFT51", "LFT52",
                 "LFT57", "LFT58", "LFT59"],
    "PY21N006": ["LACD4"],
    "PY21N008": ["LA1", "LA2", "LA3", "LA4", "LAH1", "LAH2", "LAH3", "RPH1",
                 "LBT1", "LBT2", "LBT3", "LBT4", "RA1", "RA2", "RA3", "RAH1",
                 "RAH2", "RAH3"],
}

engel_score = {
    "PY16N006": "1",
    "PY16N008": "1",
    "PY16N013": "1",
    "PY17N005": "1",
    "PY17N008": "1",
    "PY17N014": "1",
    "PY17N019": "None", #double check this
    "PY18N002": "1",
    "PY18N003": "2",
    "PY18N013": "1",
    "PY18N015": "1",
    "PY18N016": "1",
    "PY19N009": "1",
    "PY19N012": "1",
    "PY19N023": "1",
    "PY19N026": "1",
    "PY20N001": "1",
    "PY20N012": "2",
    "PY21N002": "1",
    "PY21N004": "1",
    "PY21N006": "1",
    "PY21N008": "1",
}

node_location = {
    'LA': "left amygdala",
    'LAH': "left anterior hippocampus",
    'LPH': "left posterior hippocampus",
    'LTP': "left temporal pole",
    'LBT': "left basal temporal",
    'LFOA': "which patient?",
    'LFOP': "which patient?",
    'LIN': "Left insula" ,
    'LOF': "Left orbitofrontal",
    'RA': "Right amygdala",
    'RAH': "Right anterior hippocampus",
    'LSMA': "Left supplemental motor area",
    'LM': "Left motor",
    'LS': "Left sensory area",
    'LACD': "left anterior cortical dysplasia",
    'LPCD': "Left posterior cortical dysplasia",
    'LFO': "Left frontal operculum",
    'LPO': "Left posterior operculum",
    'LAST': "Left anterior superior temporal gyrus",
    'LPST': "Left posterior superior temporal",
    'LF': "Left frontal",
    'RPH': "right posterior hippocampus",
    'RBT': "right basal temporal",
    'LCN': "Left anterior cingulate",
    'LTH': "Left temporal heterotopia",
    'LNA': "Left nodule A",
    'LND': "Left nodule D",
    'LNE': "Left nodule E",
    'RMS': "Right medial superior (medial)",
    'RMM': "Right medial tumor medial",
    'RMI': "Right medial tumor inferior",
    'RLS': "Right lateral tumor superior",
    'LH': "Left hippocampus",
    'ROF': "Right orbitofrontal",
    'RF': "Right frontal",
    'RH': "Right hippocampus",
    'LHA': "Left anterior hippocampus",
    'LHP': "Left posterior hippocampus",
    'LBTA': "Left anterior basal temporal gyrus",
    'LBTP': "Left posterior basal temporal gyrus",
    'LCNA': "Left anterior cingulate",
    'LCNM': "Left middle cingulate",
    'LCNP': "left posterior cingulate",
    'LCNS': "Left retro-splenial cingulate",
    'LINS': "Left insula",
    'LBRO': "Left Broca’s area",
    'LTG': "Left temporal grid",
    'LIF': "Left inferior frontal",
    'ALL': "Left lateral lesion 1",
    'BLL': "Left lateral lesion 2",
    'CLL': "Left lateral lesion 3",
    'DLL': "Left lateral lesion 4",
    'ELL': "Left lateral lesion 5",
    'FLL': "Left lateral lesion 6",
    'GLL': "Left lateral lesion 7",
    'BTA': "Basal temporal anterior",
    'BTMA': "Basal temporal mid-temporal",
    'BTMP': "Basal temporal posterior-temporal",
    'BTP': "Basal temporal posterior",
    'LFT': "Left fronto-temporal grid",
    'LFP': "Left fronto-parietal grid",
    'MIH': "Middle interhemispheric",
    'LPTS': "Left posterior superior temporal",
    'LAD': "Left amygdala depth",
    'LDD': "Left dysplasia depth",
    'RMFD': "Right medial frontal depth",
    'ROFD': "Right orbitofrontal depth",
    'RAD': "Right amygdala depth",
    'RHD': "Right hippocampal depth",
    'RACD': "Right anterior cingulate depth",
    'RAID': "Right anterior insular depth",
    'LMFD': "Left medial frontal depth",
    'LOFD': "Left orbitofrontal depth",
    'LHD': "Left hippocampal depth",
    'LSF': "Left superior frontal depth",
    'LSPF': "Left superior posterior frontal",
    'LIPF': "Left inferior posterior frontal depth",
    'LAN': "Left anterior nodule depth",
    'LMN': "Left middle nodule depth",
    'LPN': "Left posterior nodule depth",
    'RPCS': "Right posterior central strip",
    'RFG': "Right frontal grid",
    'RAM': "Right amygdala",
    'RPHG': "Right Para hippocampal gyrus",
    'RFUS': "Right fusiform",
    'RPIR': "Right piriform",
    'LAM': "Left amygdala",
    'RATS': "Right anterior temporal superior",
    'RATI': "Right anterior temporal inferior",
    'RABT': "Right anterior basal temporal",
    'RMBT': "right middle basal temporal",
    'RPTI': "Right posterior temporal inferior",
    'RPTS': "Right posterior temporal superior",
    'RPFS': "Right posterior frontal superior",
}